#!/usr/bin/env python3
"""Detect the CRD client's OS and rebind i3 shortcuts when it's ChromeOS.

ChromeOS swallows the Search/Launcher key (Super_L) before it reaches the
remote host, so Mod4-based i3 shortcuts silently fail. This daemon watches
the chrome-remote-desktop journal for `session-initiate` stanzas, maps the
client-id it finds against ~/.config/chrome-remote-desktop/paired-clients/
to recover the client's OS string, and — on ChromeOS — writes a conf.d file
that dual-binds every `$mod` shortcut to Mod1 (Alt) as well. For any other
client, the file is cleared so plain Mod4 continues to be the only binding.

Designed to be launched once from i3 via `exec_always` — on each i3 reload
it replaces any previous instance via fuser-style pgrep.
"""
from __future__ import annotations

import json
import os
import re
import signal
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
PAIRED_DIR = HOME / ".config/chrome-remote-desktop/paired-clients"
MAIN_CONFIG = HOME / ".config/i3/config"
CONF_D = HOME / ".config/i3/conf.d"
OUT_FILE = CONF_D / "crd-mod.conf"
STATE_FILE = HOME / ".cache/i3-crd-client.state"

CHROMEOS_CLIENT_NAMES = {"Chrome OS", "CrOS", "ChromeOS"}
CHROMEOS_MOD = "Mod1"  # Alt — reliably forwarded by CRD from ChromeOS

CLIENT_ID_RE = re.compile(r'client-id="([0-9a-f-]+)"')
LOG_FILE = HOME / ".cache/i3-crd-client.log"


def log(msg: str) -> None:
    """Write to stdout *and* a persistent file.

    When i3 launches this via `exec_always`, stdout/stderr usually go to
    `~/.xsession-errors`, but on systems where that file isn't active they
    silently disappear. The persistent log file makes diagnosis possible.
    """
    import datetime

    stamped = f"[{datetime.datetime.now().isoformat(timespec='seconds')}] {msg}"
    try:
        print(stamped, file=sys.stdout, flush=True)
    except OSError:
        pass
    try:
        LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        with LOG_FILE.open("a") as f:
            f.write(stamped + "\n")
    except OSError:
        pass


def client_name(client_id: str) -> str | None:
    path = PAIRED_DIR / f"{client_id}.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text()).get("clientName")
    except (json.JSONDecodeError, OSError):
        return None


def mod_overrides(main_cfg: str, new_mod: str, reason: str) -> str:
    """Emit a conf.d file that re-binds every top-level `bindsym $mod...` line.

    i3 allows multiple bindings for the same key chord; the most recent one
    wins, but for bindings inside a `mode "name" { ... }` block the scope is
    the mode itself, so we must NOT emit copies at the top level — that would
    collide with a top-level bindsym for the same key (e.g. `$mod+r` exits
    resize-mode inside the block *and* enters resize-mode at the top level).
    """
    lines = [
        "# Auto-generated by crd-client-detector.py — do not edit by hand.",
        f"# Reason: {reason}",
        f"# Adds {new_mod}-based copies of every top-level $mod binding.",
        "",
    ]
    brace_depth = 0
    for raw in main_cfg.splitlines():
        # Track nesting by counting unescaped braces. i3 config doesn't quote
        # braces, and no comment style needs escaping here, so a plain count
        # is sufficient for the modes we have.
        stripped = raw.lstrip()
        if brace_depth == 0 and stripped.startswith("bindsym $mod"):
            lines.append(stripped.replace("$mod", new_mod))
        brace_depth += raw.count("{") - raw.count("}")
    return "\n".join(lines) + "\n"


def current_state() -> str:
    try:
        return STATE_FILE.read_text().strip()
    except OSError:
        return ""


def set_state(value: str) -> None:
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(value + "\n")


def reload_i3() -> None:
    subprocess.run(["i3-msg", "reload"], capture_output=True)


def notify(summary: str, body: str = "") -> None:
    subprocess.run(
        ["notify-send", "-t", "3000", "-i", "input-keyboard", summary, body],
        capture_output=True,
    )


def apply_for_client(client_id: str) -> None:
    name = client_name(client_id) or f"unknown ({client_id[:8]}…)"
    is_chromeos = (client_name(client_id) or "") in CHROMEOS_CLIENT_NAMES
    target = "chromeos" if is_chromeos else "default"

    if current_state() == f"{target}:{client_id}":
        log(f"no change: already applied for {name}")
        return

    CONF_D.mkdir(parents=True, exist_ok=True)
    if is_chromeos:
        main = MAIN_CONFIG.read_text()
        OUT_FILE.write_text(
            mod_overrides(
                main,
                CHROMEOS_MOD,
                f"CRD client is {name!r}; Mod4/Search is swallowed client-side.",
            )
        )
        log(f"wrote {OUT_FILE} (Mod1 overrides for {name})")
        notify("ChromeOS client detected", f"Alt-based shortcuts enabled ({name})")
    else:
        OUT_FILE.write_text(f"# CRD client is {name!r}; default Mod4 bindings are sufficient.\n")
        log(f"cleared {OUT_FILE} (client {name!r} uses default Mod4)")
        notify("CRD client", f"Default Mod4 shortcuts ({name})")

    set_state(f"{target}:{client_id}")
    reload_i3()


def scan_recent() -> str | None:
    """Look back 1h for the latest session-initiate; return its client-id."""
    result = subprocess.run(
        [
            "journalctl",
            "-t",
            "chrome-remote-desktop",
            "--since",
            "1 hour ago",
            "--no-pager",
            "-o",
            "cat",
        ],
        capture_output=True,
        text=True,
    )
    last_id: str | None = None
    for line in result.stdout.splitlines():
        if "session-initiate" not in line:
            continue
        m = CLIENT_ID_RE.search(line)
        if m:
            last_id = m.group(1)
    return last_id


def watch_journal() -> None:
    proc = subprocess.Popen(
        [
            "journalctl",
            "-t",
            "chrome-remote-desktop",
            "-f",
            "--since",
            "now",
            "-o",
            "cat",
        ],
        stdout=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        if "session-initiate" not in line:
            continue
        m = CLIENT_ID_RE.search(line)
        if m:
            apply_for_client(m.group(1))


PID_FILE = HOME / ".cache/i3-crd-client.pid"


def kill_previous() -> None:
    """Replace any prior instance via PID file.

    Avoids `pgrep -f` because that also matches the invoking shell's cmdline
    (any process that has this script's path in its argv) and would kill the
    very bash that just launched us.
    """
    try:
        prev = int(PID_FILE.read_text().strip())
    except (OSError, ValueError):
        prev = 0
    if prev and prev != os.getpid():
        try:
            os.kill(prev, signal.SIGTERM)
        except ProcessLookupError:
            pass
    PID_FILE.parent.mkdir(parents=True, exist_ok=True)
    PID_FILE.write_text(str(os.getpid()))


def main(argv: list[str]) -> int:
    once = "--once" in argv
    kill_previous()
    log(f"starting (pid={os.getpid()}, once={once})")

    initial = scan_recent()
    if initial:
        apply_for_client(initial)
    else:
        log("no recent session-initiate found; waiting for one")

    if once:
        return 0

    try:
        watch_journal()
    except KeyboardInterrupt:
        log("interrupted")
    except Exception as e:
        log(f"fatal in watch_journal: {e!r}")
        return 1
    log("watch_journal returned (journalctl closed stdout); exiting")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
